### ISSUE TITLE
Create taste for blood (arms warrior)

### ISSUE THREAD

**Issue by Isbjorn2** [ennvina/spellactivationoverlay#104]
Taste for blood is the main a main ability in both pve and pvp for warrior.

Would make a perfect addition to the addon.

**Comment by ennvina** [comment]
Hi and thank you for your submission.

To add a new effect, we must answer these questions:
- [x] Does it proc with a buff? Yes ✅ https://www.wowhead.com/wotlk/spell=60503/taste-for-blood
- [x] Is it related to a the talent? Yes ✅ https://www.wowhead.com/wotlk/spell=56636/taste-for-blood
- [ ] Should it display a Spell Alert? (possible answer: Yes or No) If yes, please answer these questions:
  - [ ] Where? (possible answer: Top or Left or Left+Right)
  - [ ] Which texture? (open answer)
  - [x] Which size? 100%
  - [x] Change color? No (keep texture color as is)
  - [ ] Spell Alert enabled by default for all warriors? (possible answer: Yes or No)
- [x] Should it glow buttons? Yes ✅
  - [x] Which buttons should it glow? (possible answer: list of spells or abilities)
  - [ ] Which glowing buttons should glow by default? (possible answer: None, or a subset of the above list)

**Comment by Isbjorn2** [comment]
Spell alert yes = Above head like Blood surge
Overpower should glow when taste for blood is active.

**Comment by ennvina** [comment]
The Taste for Blood will be implemented as follows:
- Overpower button glows while under the effect of Taste for Blood buff
- This effect is tied to the existing Overpower option
- No Spell Alert for now, because of the conflicting location and texture

**Comment by ennvina** [comment]
Closing this issue because it was implemented in #140.

If the Spell Alert is really important, feel free to re-open the issue.
