### ISSUE TITLE
[Feature] Add support for AzeriteUI (sent a pull-request)

### ISSUE THREAD

**Issue by Goldpaw** [ennvina/spellactivationoverlay#142]
Hi! Can we add support for AzeriteUI? It uses its own custom version of LibActionButton. My users would love you even more than they already do for it! :)

I've submitted a pull-request with the necessary changes to `components/glow.lua`: 

https://github.com/ennvina/spellactivationoverlay/pull/141

**Comment by ennvina** [comment]
I'm not familiar with AzeriteUI. Thanks for the help!

I didn't know AzeriteUI buttons had their own glow/unglow functions. It definitely helps with the LibCustomGlow/LibActionButton mess that we have to deal with for libs such as ElvUI.

**Comment by ennvina** [comment]
Implemented officially now that #141 has been merged. Thanks for the help!
