### ISSUE TITLE
warrior 4t10 support 

### ISSUE THREAD

**Issue by EvanCarson** [ennvina/spellactivationoverlay#147]
Warrior 4T10 sets will trigger two stacks of slam, needs to modify the warrior profile to include that logic for slam.

**Comment by ennvina** [comment]
Hi and thank you for your feedback.

This has been reported here #145 and implemented here #146.

A beta version is available for testing
- here on GitHub https://github.com/ennvina/spellactivationoverlay/releases/tag/v0.9.5-beta
- on CurseForge https://curseforge.com/wow/addons/spellactivationoverlay/files/4838736

**Comment by EvanCarson** [comment]
Thanks!

**Comment by ennvina** [comment]
Hi, closing this issue as it was implemented in #146 and released in [v0.9.5](https://github.com/ennvina/spellactivationoverlay/releases/tag/v0.9.5). Thanks for the feedback!
