### ISSUE TITLE
Spells no longer flash with macros

### ISSUE THREAD

**Issue by cynicalfx** [ennvina/spellactivationoverlay#150]
With the latest wrath classic update (0.9.5) I noticed that spells that used to flash on the actionbars during procs no longer flash if they are a macro. I also tested by pulling the spell directly from the spellbook and placing it on my bars and they started flashing again. I tested with Flash of Light/Exorcism during Art of War, Overpower during Taste for Blood, and Execute during Sudden Death. Please let me know if you need any additional info.

**Comment by ennvina** [comment]
Hi, it still works for me as of today, with or without macros.

When you open options (in chat, type `/sao`) you can mouseover a glowing button option, it should glow the spell accordingly in your action bar. What happens when you do this?

**Comment by cynicalfx** [comment]
Thanks for the reply. I typed /sao and moused over the glowing button option and my macro abilities (Flash of Light/Exorcism) did not glow on my actionbar.

**Comment by lola97** [comment]
I have the same issue. Explosive shot in the macro that every serious hunter is using will not work, only if i use the skill from the skillbook. 
 "
#showtooltip Explosive shot
/castsequence reset=2/target Explosive Shot,Explosive Shot(Rank 3)
"

**Comment by BossAchren** [comment]
Downloaded the Dev Branch of Elvui/Tukui depending on your flavor and the issue is indeed fixed. 

https://github.com/tukui-org/ElvUI/tree/development

**Comment by ennvina** [comment]
Thanks guys for the constructive feedback. I tested your macros and they worked fine without ElvUI.
Not sure I'll do something about it if we just need the next ElvUI update, unless it takes them too much time to release it.
I already have some specific code to fix previous ElvUI issues and it's a real mess. I'd rather not add more mess if possible.

**Comment by BossAchren** [comment]
Funny, they JUST released 13.50, so its live as I type this.

**Comment by ennvina** [comment]
If anyone can confirm the new ElvUI release fixes the issue that'd be great :)

**Comment by cynicalfx** [comment]
I just tested and confirmed. No longer an issue with the newest ElvUI update (13.50). Thanks!

**Comment by ennvina** [comment]
That's some great news. Thanks again everyone for your help. Peace!
