### ISSUE TITLE
Flanking Strike

### ISSUE THREAD

**Issue by ennvina** [ennvina/spellactivationoverlay#153]
Request to track Hunter's Leg Rune: [Flanking Strike](https://www.wowhead.com/classic/spell=415320/flanking-strike)

- [ ] Does it proc from a buff? **No**, procs from a usable action, expected to be spell ID 415320
- [x] Where does it come from (baseline, talent, etc.)? **Leg Rune**
- [x] Should it display a Spell Alert? **No**
  - [ ] Where? **N/A**
  - [ ] Which texture? **N/A**
  - [ ] Which size? **N/A**
  - [ ] Change color? **N/A**
  - [ ] Spell Alert enabled by default for all hunters? **N/A**
- [x] Should it glow buttons? **Yes**, because this ability can be reset by chance when casting Raptor Strike
  - [x] Which buttons should it glow? [**Flanking Strike**](https://www.wowhead.com/classic/spell=415320/flanking-strike)
  - [x] Which glowing buttons should glow by default? **Flanking Strike**

**Comment by ennvina** [comment]
Implemented in 1.1.0-beta with the following assumptions (confirmation needed by hunters, please!)
- Glowing Button with spell ID 415320
- Spell Alert displayed when the action is usable
- Spell Alert uses texture `tooth_and_claw` displayed "Left + Right"

![image](https://github.com/ennvina/spellactivationoverlay/assets/75951742/f6aa72dd-6898-456d-962a-7e24ed5151b9)

**Comment by rainecheck** [comment]
This texture is just permanently active on a fresh SoD Hunter once you engage in combat.

**Comment by ennvina** [comment]
> This texture is just permanently active on a fresh SoD Hunter once you engage in combat.

Hi and thank you for your feedback. This issue has been fixed in version 1.1.1, released today. Make sure to check it out :)

**Comment by oerp-odoo** [comment]
@ennvina to me from version `1.15.0`, flanking strike is bugged. Whenever flanking strike is off cool down, it always glows as active, even though no proc was triggered or anything. had to downgrade to `1.14` to disable this behavior.

**Comment by ennvina** [comment]
> @ennvina to me from version `1.15.0`, flanking strike is bugged. Whenever flanking strike is off cool down, it always glows as active, even though no proc was triggered or anything. had to downgrade to `1.14` to disable this behavior.

Hi, and thank you for your feedback.

I believe your version numbers are wrong. The last addon version is 1.1.3, released a few days ago.

We are aware of issues about the Flanking Strike ability. It is kinda intended to have it glow even without a 'proc' and, although there's not much we can do about it, we will try to make it less annoying.

There is another issue where the effect is visible when you get the buff after casting the ability. This is not intended at all and shall be fixed eventually.

**Comment by oerp-odoo** [comment]
> > @ennvina to me from version `1.15.0`, flanking strike is bugged. Whenever flanking strike is off cool down, it always glows as active, even though no proc was triggered or anything. had to downgrade to `1.14` to disable this behavior.
> 
> Hi, and thank you for your feedback.
> 
> I believe your version numbers are wrong. The last addon version is 1.1.3, released a few days ago.
> 
> We are aware of issues about the Flanking Strike ability. It is kinda intended to have it glow even without a 'proc' and, although there's not much we can do about it, we will try to make it less annoying.
> 
> There is another issue where the effect is visible when you get the buff after casting the ability. This is not intended at all and shall be fixed eventually.

Oh, right. It was game version, not addon version. Though with latest version, I was not even able to disable that glow. If I would go to settings and uncheck boxes, to not show it, it would still glow. So only reverting to older version, would disable it:).

But shouldn't that glow trigger when you do a proc after raptor strike?, indicating that you can attack again with flanking strike (as it resets flanking strike CD)? Making it glow just off CD seems weird as it would glow forever and without even going to combat.

**Comment by ennvina** [comment]
> Oh, right. It was game version, not addon version. Though with latest version, I was not even able to disable that glow. If I would go to settings and uncheck boxes, to not show it, it would still glow. So only reverting to older version, would disable it:).

If the spell is already glowing and you disable the checkbox, it will not un-glow it immediately. The current design is to prevent future glows. To force an un-glow, one may disable the checkbox and then reload UI.

> But shouldn't that glow trigger when you do a proc after raptor strike?, indicating that you can attack again with flanking strike (as it resets flanking strike CD)? Making it glow just off CD seems weird as it would glow forever and without even going to combat.

This one is a tough call. As a player, I would expect the ability to glow only on resets. But this has two drawbacks:
1. it is almost impossible to detect the ability was made available due to a reset. The game only tells "the ability is ready". It doesn't tell "the ability is ready because there was a reset".
2. we have to decide a duration for which the spell alert and glowing buttons should be active. Because the ability is available "forever", we might display it forever (PS. this is what the addon currently does) or we might display it for a limited duration.

We could solve problem 1 by estimating when the ability cooldown is _supposed_ to be available with full cooldown, and when it becomes available sooner, it indicates there was a proc. We could also cross check with Raptor Strike casts (which we can detect) to reduce chance of detecting false positives.

This is not too complex to do, but this would be weird if Raptor Strikes resets Flanking Strike e.g. 1 secs before FS cooldown. The addon would tell "hey you are lucky, you got a proc" while in fact the ability would have been usable after the GCD anyway. We could implement a "don't show proc if it happens less than $x$ secs before the cooldown end time" but choosing the $x$ number would not be easy, not to mention it would be cumbersome.

For problem 2, displaying the effect for a limited duration sounds like a reasonable choice, but if so, for how long? If we display it for e.g. 10 secs, the player might s/he has up to 10 secs to cast the ability, otherwise the ability is lost. But in practice, casting it 12 or 15 secs later is totally possible. So, with this 10-sec example, it would fool the player into rushing the cast, while in fact there's no rush.

**Comment by ennvina** [comment]
Closing this issue, as no problem has been reported in a long time. Plus, recent development should have made things even smoother.
