### ISSUE TITLE
Fingers of Frost (SoD)

### ISSUE THREAD

**Issue by ennvina** [ennvina/spellactivationoverlay#154]
Request to track Mage's Chest Rune: [Fingers of Frost](https://www.wowhead.com/classic/spell=400647/fingers-of-frost)

It would probably re-use the Fingers of Frost effect from Wrath of the Lich King, although we need confirmation that the spell ID remains the same.

**Comment by ennvina** [comment]
> Got one of my mates to check. The ID of the proc, at least at level 17, is `400670`, this one: https://www.wowhead.com/classic/spell=400670/fingers-of-frost

I've got two other sources who confirmed it, with two charges.

Wowhead mentions 400669 for one charge, can you check the spell ID when you have one charge left?

**Comment by Soothx** [comment]
> > Got one of my mates to check. The ID of the proc, at least at level 17, is `400670`, this one: https://www.wowhead.com/classic/spell=400670/fingers-of-frost
> 
> I've got two other sources who confirmed it, with two charges.
> 
> Wowhead mentions 400669 for one charge, can you check the spell ID when you have one charge left?

I helped my friend make a WeakAura with the 400670 ID as the only one, and it is tracked as stacks on it. The WA showed the number of stacks remaining, and was visible at both 2 and 1 stacks.

**Comment by ennvina** [comment]
Closing issue, because the ability has been tested successfully for months.
