### ISSUE TITLE
Ice Lance (SoD)

### ISSUE THREAD

**Issue by ennvina** [ennvina/spellactivationoverlay#155]
Request to track Mage's Glove Rune: [Ice Lance](https://www.wowhead.com/classic/spell=400640/ice-lance)

The idea would be to make Fingers of Frost glow when the target is frozen, similar to the effect from Wrath of the Lich King, although we need confirmation that the spell ID remains the same.

**Comment by Soothx** [comment]
The spell ID is the same at `400640`.

**Comment by ennvina** [comment]
> The spell ID is the same at `400640`.

Confirmed. Thanks for the help :)

**Comment by ennvina** [comment]
Closing issue, because the ability has been tested successfully for months.
