### ISSUE TITLE
Victory Rush (SoD)

### ISSUE THREAD

**Issue by ennvina** [ennvina/spellactivationoverlay#159]
Request to track Warrior's Glove Rune: [Victory Rush](https://www.wowhead.com/classic/spell=402927/victory-rush)

It would probably re-use the Victory Rush glowing button from Wrath of the Lich King, although we need confirmation that the spell ID remains the same.

**Comment by ennvina** [comment]
Implemented in 1.1.0-beta with the same code for Victory Rush in Wrath flavor, except this time the spell ID is `402927`.

**Comment by boktai1000** [comment]
I posted this comment on Curseforge of the current status with Victory Rush-
https://legacy.curseforge.com/wow/addons/spellactivationoverlay?comment=308

I encountered an odd error with Victory Rush for Warrior on SoD where I don't get the activation glow effect on my action bar when it procs or is available, but if I go into the options menu for the addon and hover over Victory Rush it will glow as expected - of course that is just previewing the menu option and not actually reflective of actual gameplay.

Cheers!

![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/795a9dd3-b988-4d1b-8da6-0049fe7344d9)

![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/3a348d8e-4d15-4145-8728-1e3d0a09c6e4)

**Comment by ennvina** [comment]
Solution implemented in v1.1.2.

**Comment by boktai1000** [comment]
Still having issues with it working on 1.1.3

![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/de9ff8a9-f4d7-4f71-925a-187d5443e933)
![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/856aab8d-9439-4f7e-bde9-736e448a942f)

**Comment by boktai1000** [comment]
I also briefly tested during the day with 1.1.2 but didn't end up reporting it, that when I was killing some Boars outside of Ironforge the very first kill didn't make the glow pop, and I was toggling the Debug to chat and subsequently it seemed to start working after that and reloaded my UI and continued to work. Just decided to leave it there, but now that it's not working again, I wanted to let you know in case. Unfortunately, I did not save the screenshots I took on 1.1.2 at the time but have my anecdote above to go off of. Thank you :) 

![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/e70050d4-a745-4c58-bf2b-eec13c4ce313)

**Comment by ennvina** [comment]
Hi, I'm having no issues so far with my SoD Warrior. The "Write to Debug Chatbox" option should display this message in the chatbox at some point:
![image](https://github.com/ennvina/spellactivationoverlay/assets/75951742/ae833c61-f4a2-4463-918e-c3dd2464e02e)
This happens once per rune, usually upon login, although it may happen at different times. You can re-apply Victory Rush on your gauntlets to force re-detecting runes (although it's not necessary in theory). This message will not appear if automatic rune detection already worked.

**Comment by boktai1000** [comment]
Sounds good! I believe I noticed it right after logging in and testing. It's certainly been working fairly consistently, perhaps all the time since. I can keep an eye on it if I notice anything in the future, and apply your debugging methodology to track things down. At least when this issue was opened, I could say it was not working - and now it is, so up to you if you'd like to keep it open for any Victory Rush related issues, or if new issues should be opened and tracked appropriately.

Happy Holidays and take care!

**Comment by ennvina** [comment]
Thanks for the feedback. I prefer keeping SoD-related issues open for now. Closed issues are not visible by default. By keeping issues open, everyone can easily see these nice places to share information for each rune.

**Comment by boktai1000** [comment]
![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/e694762f-b76b-46a9-b0e6-8b2f962f5d5e)
![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/a79a689c-c9d7-47b4-88bc-8df8454cd3b6)

Debug enabled, nothing written to chat
![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/81282d98-9f92-4c27-bbac-a4018d0d96b0)

Mouseover does trigger it in options
![image](https://github.com/ennvina/spellactivationoverlay/assets/9054563/19945c68-ab43-4c87-903f-87357178a4c9)

**Comment by boktai1000** [comment]
In this case, I definitely did not apply Victory Rush to my gauntlets today but I noticed it today as a problem. I am leveling a new fresh Warrior. It only started working after I moused over in the SpellActivationOverlay settings as shown above.

I believe there may be something wrong with one of the following then if I'm guessing that something with automatic rune detection isn't working properly on login. I think perhaps I could probably re-trigger this behavior by deleting my WTF SavedVariables for this character to re-trigger this?

**Comment by ennvina** [comment]
There is something I do not understand: if you did not apply Victory Rush to your gauntlets, then I would assume you should not have the Victory Rush ability in your action bar. Instead, there should be a filler like a "Gauntlet Rune" ability that does nothing.

**Comment by ennvina** [comment]
@boktai1000 I think I have nailed the bug that caused your issue. It required a lot of more effort than what it deserved. Anyway, a fix is on its way.

In the meantime, you can download [this file](https://github.com/ennvina/spellactivationoverlay/files/14016773/rune.zip) and unzip it in the components subfolder:

`$WoW/_classic_era_/Interface/AddOns/SpellActivationOverlay/components`
(where `$WoW` is your WoW installation folder, usually `C:\Program Files (x86)\World of Warcraft`)

It should overwrite `rune.lua` which already exists in this folder.

**Comment by ennvina** [comment]
Closing issue, because the ability has been tested successfully for months.
