### ISSUE TITLE
Shaman - Maelstrom Weapon, Power Surge (SoD)

### ISSUE THREAD

**Issue by Amanthuul** [ennvina/spellactivationoverlay#173]
Pretty much these are interactions:
![image](https://github.com/ennvina/spellactivationoverlay/assets/18071324/65236aa8-b39f-492b-b71b-f74e670e5730)

For MW and Molten blast overlap - idk what can be done here. Shifting one of top of another maybe?

As for Power Surge - it maybe can be done as it was in WoD? (with lavaburst proc texture? echo of the elements would fit nicely though, but it's used for clearcasting)
If both overlays are enabled, left one will be Power Surge, right one - Clearcasting. If only one of them - both sides occupied by proc.

Looked like that back in WoD
![image](https://github.com/ennvina/spellactivationoverlay/assets/18071324/941a0fdf-0030-4908-ac02-69c9999f896d)

**Comment by ennvina** [comment]
Hi, I'm closing this issue because the corresponding pull request (or, more exactly, its follow-up #184) has been merged. Thanks again for your help :)
