### ISSUE TITLE
Missing Texture of Art of War in SoD Paladin

### ISSUE THREAD

**Issue by Bernouil** [ennvina/spellactivationoverlay#195]
![image](https://github.com/ennvina/spellactivationoverlay/assets/131319710/8308f16f-e436-46a6-a5e2-fe8b0d4778cd)

**Comment by ennvina** [comment]
Hi, and thank you for your report.

These textures are used by Wrath talents:
- `Art_of_War` texture is used by [Art of War](https://www.wowhead.com/wotlk/spell=53489/the-art-of-war)
- `Daybreak` texture is used and [Infusion of Light](https://www.wowhead.com/wotlk/spell=53576/infusion-of-light)

To my knowledge, there is no such rune in Season of Discovery (at least not yet). These effects will be disabled in SoD to avoid these confusing messages.
