### ISSUE TITLE
Warlock (Cata)

### ISSUE THREAD

**Issue by ennvina** [ennvina/spellactivationoverlay#269]
Request to support the Warlock class in Cataclysm.

### 😱 Affliction

- [x] Drain Soul (unchanged)
- [x] Nightfall / Shadow Trance (unchanged)

### 😈 Demonology

- [x] Molten Core (updated)
  - Must no longer glow Soul Fire
- [x] Decimation (unchanged)

### ☢️ Destruction

- [x] Backdraft (new) [talent](https://www.wowhead.com/cata/spell=47258/backdraft) / [buff rank 1](https://www.wowhead.com/cata/spell=54274/backdraft) / [buff rank 2](https://www.wowhead.com/cata/spell=54276/backdraft) / [buff rank 3](https://www.wowhead.com/cata/spell=54277/backdraft)
  - Must glow buttons of [Shadow Bolt](https://www.wowhead.com/cata/spell=686/shadow-bolt), [Incinerate](https://www.wowhead.com/cata/spell=29722/incinerate) and [Chaos Bolt](https://www.wowhead.com/cata/spell=50796/chaos-bolt)
- [x] Shadowburn (new) [talent](https://www.wowhead.com/cata/spell=17877/shadowburn)
  - Must glow button of Shadowburn
  - Talent exists since Vanilla, but up until Wrath it did cost a Soul Shard, so spamming it was not ideal
  - Starting from Cataclysm, it is nice to spam it
- [x] Backlash (unchanged)
- [x] Empowered Imp (updated)
  - Must now glow [Soul Fire](https://www.wowhead.com/cata/spell=6353/soul-fire)

**Comment by ennvina** [comment]
Implemented in #273.

**Comment by neeckola** [comment]
any chance to add warlock 4t11 proc?

**Comment by ennvina** [comment]
Reopened for Shadowburn.

**Comment by ennvina** [comment]
> any chance to add warlock 4t11 proc?

Hi and thank you for your feedback.
That is a nice suggestion, I have submitted a dedicated issue #296
