### ISSUE TITLE
Debug script left in latest version

### ISSUE THREAD

**Issue by Lanksty** [ennvina/spellactivationoverlay#282]
Debug script seems to be left in the latest version of the addon which is now flooding the chat during combat (see attached image)
![image](https://github.com/ennvina/spellactivationoverlay/assets/100813991/3bac65bc-ab25-4dd3-a243-67f15375e566)

**Comment by ennvina** [comment]
Hi, and thank you for your feedback. This was fixed in version 1.4.2. Please download it and tell us if it worked.

**Comment by ennvina** [comment]
Closing this issue, as this was fixed and released a few weeks ago. Thanks again for your feedback.
