### ISSUE TITLE
"un-maring aura xxxx which had count of nil" shows up for every spell activation update: may 10 1.15.2 game version: classic era

### ISSUE THREAD

**Issue by pulpzzz** [ennvina/spellactivationoverlay#283]
"un-maring aura xxxx which had count of nil" shows up for every spell activation
update: may 10 1.15.2
game version: classic era

**Comment by ennvina** [comment]
Hi and thanks for the feedback. This was a mistake that has been fixed in version 1.4.2.

**Comment by ennvina** [comment]
Closing this issue, as it has been fixed and released officially. Thanks again for your help.
