### ISSUE TITLE
Infusion of Light (Holy Paladin Critical Holy Shock Proc) missing

### ISSUE THREAD

**Issue by Jaesaboyx** [ennvina/spellactivationoverlay#31]
Currently you only implemented "Art of War" for Ret Paladins.
There's a proc if you do a critical hit with Holy Shock, called "Infusion of Light" (https://www.wowhead.com/wotlk/spell=53576/infusion-of-light).
Looking like this on retail: https://i.imgur.com/EdJE0S8.png

If you can please implement it. I will also try to create a pull request asap if I find time. :)

**Comment by ennvina** [comment]
Thanks for the suggestion. Looks like an excellent candidate.

The [latest branch](https://github.com/ennvina/spellactivationoverlay/tree/infusion-of-light) implements this spell.

It procs when one of these buffs is found:
- [Infusion of Light (Rank 1)](https://www.wowhead.com/wotlk/spell=53672/infusion-of-light)
- [Infusion of Light (Rank 2)](https://www.wowhead.com/wotlk/spell=54149/infusion-of-light)

I’m currently using the "Daybreak" texture:
![Daybreak](https://wow.tools/casc/preview/chash?buildconfig=806f4fd265de05a9b328310fcc42eed0&cdnconfig=b225a5d105393ef582066157f7dd34fc&filename=textures%2Fspellactivationoverlays%2Fdaybreak.blp&contenthash=21d63f5488badcff977ffb42cca4a99e)

Here is a demonstration of what I've come up with: [Infusion of Light](https://cdn.discordapp.com/attachments/630388534087385099/1004537877629243472/infusion-of-light.gif)

What do you think of it?

If you have a beta key, you can test it by installing the addon manually:
https://github.com/ennvina/spellactivationoverlay/archive/refs/heads/infusion-of-light.zip
(you will need to rename the folder from `spellactivationoverlay-infusion-of-light` to `SpellActivationOverlay`)

**Comment by ennvina** [comment]
Implemented in #32
