### ISSUE TITLE
Vehicle UI issue in/during combat

### ISSUE THREAD

**Issue by Pocokk** [ennvina/spellactivationoverlay#323]
Hey there!

I'm having some problem with UI when I enter/sit in vehicles during combat in instance environment, see this video:

https://streamable.com/svjgpx

Some people told me this addon of Yours could cause such behavior with modifying/"touching" bars and whatnot, is there any possibility to that or the addon can't be the issue here? 

Thank you

**Comment by denkololz** [comment]
Having similar issue, came to this github to look for this exact issue. Glad to see i found the culprit. Happens when you exit the MC on nefarian aswell. kind of unplayable.

**Comment by ennvina** [comment]
Hi, the new release should fix this issue. Feel free to re-open it if the bug still happens.
