### ISSUE TITLE
wow sod warlock

### ISSUE THREAD

**Issue by Blakie21** [ennvina/spellactivationoverlay#328]
i know that the addon was created primarly for wotlk/cataclysm but in wow sod the addon doesnt show any other options of highlighting except the proc of nightfall+ shadowbolt. can we have more options here? or is it bugging?

**Comment by ennvina** [comment]
Hi and thank you for your feedback. As opposed to Wrath and Cataclysm, there aren't many things to track for Warlocks in Season of Discovery. Fortunately, phase 4 was generous for Warlocks, and the addon will support more effects in the near future, as detailed in #331.

**Comment by ennvina** [comment]
Closing this issue, as this hasn't been updated in more than 2 months, and #331 has been implemented and released officially a few weeks ago.
