### ISSUE TITLE
Heating up during Hot Streak

### ISSUE THREAD

**Issue by Cheesehyvel** [ennvina/spellactivationoverlay#42]
You can get heating up if you get a crit while you have hot streak active.
This has been tested and confirmed on beta.

Currently this addon does not support this.

**Comment by ennvina** [comment]
Actually, the addon does support this.

1. if you cast Fireball and get a crit, the addon enters the "heating up" state, which displays the small alert
2. if you cast a second Fireball and get a crit, the addon enters the "hot streak" state, which hides the small alert and shows the big alert
3. if you cast a third Fireball and get a crit, the addon enters a special state "hot streak - heating up", it does not show the small alert, only the big alert is visible
4. if you now cast Pyroblast, it hides the big alert, and the addon switches to the "heating up" state, which displays the small alert

This is designed to match the reference client i.e., Retail.

I’d like to know your experience:
- you don’t see the small alert in step 4
  - this would be a bug
  - in this case, please describe what you did and what the combat log tells you
- you don’t see the small alert in step 3
  - this is intended and matches the reference client
- or you see another problem, in which case I’m all ears

**Comment by Cheesehyvel** [comment]
Oh my mistake. It was step 3 I was referring to.
I don't play retail so I wasn't sure of the intention.
The reason I mentioned it is because it affects the rotation if heating up and hot streak is up at the same time.

**Comment by ennvina** [comment]
That’s interesting feedback. Then maybe I’ll add an option eventually, so that mages who rely on this info can have it. Or maybe even put it by default, I don’t know.
