### ISSUE TITLE
Timer option

### ISSUE THREAD

**Issue by XiconQoo** [ennvina/spellactivationoverlay#46]
Can you please add an option, to show time remaining.

**Comment by ennvina** [comment]
Hi and thank you for the feedback.
I thought I already created an issue for this, thank you for creating it :)
It is something I’d like to add, but I must overcome a few technical difficulties to do it correctly.
Stay tuned!

**Comment by ennvina** [comment]
Suggestion: the normal texture, and the same texture with reduced transparency.

As time passes, the transparency texture "munches" the normal one, up until the whole is texture is semi-transparent, which means the buff has expired. Shortly after, the texture becomes completely hidden (in 0.1-ish seconds).

**Comment by XiconQoo** [comment]
I think people might like this, but it misses the point of this ticket. A transparency feedback for a duration is non-intuitive (at least for me). I cannot exactly say if a picture is at 30% or 50% transparency. I much prefer a timer in a 0.1 second accuracy.

**Comment by ennvina** [comment]
> I think people might like this, but it misses the point of this ticket. A transparency feedback for a duration is non-intuitive (at least for me). I cannot exactly say if a picture is at 30% or 50% transparency. I much prefer a timer in a 0.1 seconds accuracy.

Just to be clear, I do not intend to fade out the texture progressively. There will be two very distinct levels of opacity, one of them will grow and the other one will shrink.

I am currently considering using half opacity of the main texture. So, if the main texture is at 80% opacity, the "timeout" texture will be at 40% opacity. I think it will be clear enough, but if it's not clear, I will simply make the "timeout" texture even less opaque.

**Comment by ennvina** [comment]
Implemented in #160.

The half-transparent texture uses 25% opacity so that the visual effect stands out a bit more.

Closing this issue as the current solution fully fixes the issue. Feel free to reply to this issue or re-open it if the current solution is not good.
