### ISSUE TITLE
Overlays remain shown if buffs fade during loading screens

### ISSUE THREAD

**Issue by Xaero252** [ennvina/spellactivationoverlay#65]
For example if a buff was active at the end of an Arena or Battleground and a player clicks "Leave Battle" the buffs will remain shown even though they are not on the player.
This can easily be solved by hooking "PLAYER_ENTERING_WORLD" which fires on login and at the end of any loading screen, followed by checking for the buffs and clearing if they aren't present. One note would be to avoid clearing the "Heating Up" overlay since Heating Up doesn't have an actual buff but does have infinite duration. There is a separate issue already open for suggestions on handling the Heating Up overlay outside of combat.

**Comment by ennvina** [comment]
Related to #67.

**Comment by ennvina** [comment]
Fixed in #76.

Please read the Pull Request comment for more details.

Heating Up will be cleared, but overall feedback tends to favor this behavior anyway. Also, Heating Up will fade out eventually, when #57 will be implemented.

PS. this fix will be included in the next release.

**Comment by ennvina** [comment]
Closing this issue after 1 month of inactivity after declaring the issue was probably fixed.
