### ISSUE TITLE
Shaman: Tidal Waves

### ISSUE THREAD

**Issue by Paladin341** [ennvina/spellactivationoverlay#66]
For the Shaman class, Resto spec is missing the Spell Alert for Tidal Waves.

It uses the high_tide.blp texture in the files. "textures/spellactivationoverlays/high_tide.blp"

The spell stacks up to two times and used after casting Chain Heal or Riptide. I think it would be useful to add. I really enjoy the addon so far.  Thanks for your hard work. 👍

**Comment by ennvina** [comment]
Hi and thank you for your feedback.

It looks like a good candidate for a new Spell Alert. And thank you for finding the texture file.

Considering High Tide was introduced in Warlord of Draenor, we must "invent" an appearance. For the record, high_tide.blp is a "top" texture, and the talent gives 2 charges of Tidal Waves.

Here are the current solutions:
- the texture shall be hidden on top, with the same appearance for 1 or 2 charges
- the texture shall be hidden on top, normal size with 2 charges and small size with 1 charge
- the texture shall be rotated 90 degrees and displayed left/right (left = 1 charge, left+right = 2 charges)

Feel free to tell if one of it would be preferred and/or suggest another one.

**Comment by Paladin341** [comment]
I did some digging into it.  I think maybe the High Tide texture is not the best for Tidal Waves talent buff since it is really large. There was this weak aura I used in Legion where there were small blue watery orbs to the left and the right of the character (since there are 2 charges).

This Shaman Weak Aura Package is for Legion.
 https://wago.io/SkCQSeibG 
 Specifically the Tidal Waves were based on the texture "Monk_ForceSpere_Orb.m2"
 
Maybe you could use that instead since it is smaller and takes up less space than High Tide.

**Comment by Paladin341** [comment]
Ah I just realized that it switches from then to be a Model instead of a texture.  Maybe we can get close to a blue water orb texture?

**Comment by ennvina** [comment]
I haven’t used models for now, and I’d rather stick to textures for as long as possible.

Small images are technically possible in the top-left and top-right corners, but I guess they would look weird, because I don’t know of any Spell Alert from Retail which uses these locations.

If the High Tide texture is too big, we can easily resize it. For example, I already display the Impact texture at 80% scale for Firestarter and Decimation because the full texture looks too heavy.

**Comment by RobertGasparian** [comment]
Thanks for the awesome addon :)
Is there any news, when can we expect this feature?

**Comment by ennvina** [comment]
Implemented in #100.

See PR for more information.
