### ISSUE TITLE
Ret Paladin T10 2pc

### ISSUE THREAD

**Issue by ennvina** [ennvina/spellactivationoverlay#72]
Back in WotLK OG, the very popular addon CLCRet displayed a proc for the 2p bonus of the Retribution Paladin tier-10 set.

https://www.wowhead.com/wotlk/spell=70765/item-paladin-t10-retribution-2p-bonus

~~Since CLCRet is one of the addons which contributed to eventually add Spell Alerts to all players in Cataclysm, it would be a nice tribute to add these CLCRet procs.~~ <sup>_[There is little evidence supporting this fact]_</sup>

~~https://cdn.discordapp.com/attachments/1013194772858540086/1019770226885275748/divine-purpose_art-of-war.jpg~~

~~In the above image, Art of War is the top texture and T10 2p bonus was the lest/right texture. In CLCRet, these textures could be swapped between top and left/right, so it would be nice to have an option to swap as well.~~ <sup>_[Do not swap texture location so late in the expansion]_</sup>

It will be difficult to test this proc because we probably won’t have access to a PTR with T10-geared pre-made characters. And testing on Retail is not an option either, because the bonus no longer exists in its Wrath form.

Open questions:
- for how long should the spell alert stay visible / should the button glow? For a limited duration? Up until the player casts DS?
- do we display an alert / glowing button if the 2p bonus procs but Divine Storm was already _off_ cooldown?

**Comment by ennvina** [comment]
Standard questions for a new proc:

- [ ] Does it proc from a buff? **Unsure**, maybe there is [a buff when the effect procs](https://www.wowhead.com/wotlk/spell=70765/item-paladin-t10-retribution-2p-bonus), maybe not
- [x] Is it baseline or related to a talent? **Neither**, it comes with a tier set bonus
- [ ] Should it display a Spell Alert? _TBD_
  - [ ] Where? _TBD_
  - [ ] Which texture? _TBD_ please read [these instructions](https://discord.com/channels/1013194771969355858/1013199984084127794/1013229314495479828) to find a texture
  - [ ] Which size? _TBD_ (probably 100%)
  - [ ] Change color? _TBD_ (probably not - keep texture color as is)
  - [ ] Spell Alert enabled by default for all paladins? _TBD_ (probably yes)
- [x] Should it glow buttons? **Yes**
  - [x] Which buttons should it glow? [**Divine Storm**](https://www.wowhead.com/wotlk/spell=53385/divine-storm)
  - [x] Which glowing buttons should glow by default? **Divine Storm**

**Comment by mpfleming36** [comment]
So I was able to add the button glow for what appears to be when it comes off CD, but it never stops glowing. By default when starting the game or reloading UI, it never goes away. I was thinking max 10 seconds it should still glow since that is the original CD, but not sure how to implement it. Would I need to use something similar to the RevengeHandler for warrior?

**Comment by ennvina** [comment]
#210 implemented in #221.

Although it does not really track cooldown resets, it helps players to know when they can smash this fancy Divine Storm button.
